{
    key.Unshifted( ecodes.KEY_GRAVE ) : key.Shifted( ecodes.KEY_LEFTBRACE ),
    key.Unshifted( ecodes.KEY_1 ) : key.Unshifted( ecodes.KEY_1 ),
    key.Unshifted( ecodes.KEY_2 ) : key.Unshifted( ecodes.KEY_2 ),
    key.Unshifted( ecodes.KEY_3 ) : key.Unshifted( ecodes.KEY_3 ),
    key.Unshifted( ecodes.KEY_4 ) : key.Unshifted( ecodes.KEY_4 ),
    key.Unshifted( ecodes.KEY_5 ) : key.Unshifted( ecodes.KEY_5 ),
    key.Unshifted( ecodes.KEY_6 ) : key.Unshifted( ecodes.KEY_6 ),
    key.Unshifted( ecodes.KEY_7 ) : key.Unshifted( ecodes.KEY_7 ),
    key.Unshifted( ecodes.KEY_8 ) : key.Unshifted( ecodes.KEY_8 ),
    key.Unshifted( ecodes.KEY_9 ) : key.Unshifted( ecodes.KEY_9 ),
    key.Unshifted( ecodes.KEY_0 ) : key.Unshifted( ecodes.KEY_0 ),
    key.Unshifted( ecodes.KEY_MINUS ) : key.Unshifted( ecodes.KEY_MINUS ),
    key.Unshifted( ecodes.KEY_EQUAL ) : key.Shifted( ecodes.KEY_MINUS ),

    key.Unshifted( ecodes.KEY_Q ) : key.Unshifted( ecodes.KEY_Q ),
    key.Unshifted( ecodes.KEY_W ) : key.Unshifted( ecodes.KEY_W ),
    key.Unshifted( ecodes.KEY_E ) : key.Unshifted( ecodes.KEY_E ),
    key.Unshifted( ecodes.KEY_R ) : key.Unshifted( ecodes.KEY_R ),
    key.Unshifted( ecodes.KEY_T ) : key.Unshifted( ecodes.KEY_T ),
    key.Unshifted( ecodes.KEY_Y ) : key.Unshifted( ecodes.KEY_Y ),
    key.Unshifted( ecodes.KEY_U ) : key.Unshifted( ecodes.KEY_U ),
    key.Unshifted( ecodes.KEY_I ) : key.Unshifted( ecodes.KEY_I ),
    key.Unshifted( ecodes.KEY_O ) : key.Unshifted( ecodes.KEY_O ),
    key.Unshifted( ecodes.KEY_P ) : key.Unshifted( ecodes.KEY_P ),
    key.Unshifted( ecodes.KEY_LEFTBRACE ) : key.Unshifted( ecodes.KEY_RIGHTBRACE ),
    key.Unshifted( ecodes.KEY_RIGHTBRACE ) : key.Unshifted( ecodes.KEY_BACKSLASH ),
    key.Unshifted( ecodes.KEY_BACKSLASH ) : key.Unshifted( ecodes.KEY_YEN ),

    key.Unshifted( ecodes.KEY_A ) : key.Unshifted( ecodes.KEY_A ),
    key.Unshifted( ecodes.KEY_S ) : key.Unshifted( ecodes.KEY_S ),
    key.Unshifted( ecodes.KEY_D ) : key.Unshifted( ecodes.KEY_D ),
    key.Unshifted( ecodes.KEY_F ) : key.Unshifted( ecodes.KEY_F ),
    key.Unshifted( ecodes.KEY_G ) : key.Unshifted( ecodes.KEY_G ),
    key.Unshifted( ecodes.KEY_H ) : key.Unshifted( ecodes.KEY_H ),
    key.Unshifted( ecodes.KEY_J ) : key.Unshifted( ecodes.KEY_J ),
    key.Unshifted( ecodes.KEY_K ) : key.Unshifted( ecodes.KEY_K ),
    key.Unshifted( ecodes.KEY_L ) : key.Unshifted( ecodes.KEY_L ),
    key.Unshifted( ecodes.KEY_SEMICOLON ) : key.Unshifted( ecodes.KEY_SEMICOLON ),
    key.Unshifted( ecodes.KEY_APOSTROPHE ) : key.Shifted( ecodes.KEY_7 ),

    key.Unshifted( ecodes.KEY_Z ) : key.Unshifted( ecodes.KEY_Z ),
    key.Unshifted( ecodes.KEY_X ) : key.Unshifted( ecodes.KEY_X ),
    key.Unshifted( ecodes.KEY_C ) : key.Unshifted( ecodes.KEY_C ),
    key.Unshifted( ecodes.KEY_V ) : key.Unshifted( ecodes.KEY_V ),
    key.Unshifted( ecodes.KEY_B ) : key.Unshifted( ecodes.KEY_B ),
    key.Unshifted( ecodes.KEY_N ) : key.Unshifted( ecodes.KEY_N ),
    key.Unshifted( ecodes.KEY_M ) : key.Unshifted( ecodes.KEY_M ),
    key.Unshifted( ecodes.KEY_COMMA ) : key.Unshifted( ecodes.KEY_COMMA ),
    key.Unshifted( ecodes.KEY_DOT ) : key.Unshifted( ecodes.KEY_DOT ),
    key.Unshifted( ecodes.KEY_SLASH ) : key.Unshifted( ecodes.KEY_SLASH ),

    key.Unshifted( ecodes.KEY_ESC ) : key.Unshifted( ecodes.KEY_ESC ),
    key.Unshifted( ecodes.KEY_BACKSPACE ) : key.Unshifted( ecodes.KEY_BACKSPACE ),
    key.Unshifted( ecodes.KEY_ENTER ) : key.Unshifted( ecodes.KEY_ENTER ),
    key.Unshifted( ecodes.KEY_SPACE ) : key.Unshifted( ecodes.KEY_SPACE ),


    key.Shifted( ecodes.KEY_GRAVE ) : key.Shifted( ecodes.KEY_EQUAL ),
    key.Shifted( ecodes.KEY_1 ) : key.Shifted( ecodes.KEY_1 ),
    key.Shifted( ecodes.KEY_2 ) : key.Unshifted( ecodes.KEY_LEFTBRACE ),
    key.Shifted( ecodes.KEY_3 ) : key.Shifted( ecodes.KEY_3 ),
    key.Shifted( ecodes.KEY_4 ) : key.Shifted( ecodes.KEY_4 ),
    key.Shifted( ecodes.KEY_5 ) : key.Shifted( ecodes.KEY_5 ),
    key.Shifted( ecodes.KEY_6 ) : key.Unshifted( ecodes.KEY_EQUAL ),
    key.Shifted( ecodes.KEY_7 ) : key.Shifted( ecodes.KEY_6 ),
    key.Shifted( ecodes.KEY_8 ) : key.Shifted( ecodes.KEY_APOSTROPHE ),
    key.Shifted( ecodes.KEY_9 ) : key.Shifted( ecodes.KEY_8 ),
    key.Shifted( ecodes.KEY_0 ) : key.Shifted( ecodes.KEY_9 ),
    key.Shifted( ecodes.KEY_MINUS ) : key.Shifted( ecodes.KEY_RO ),
    key.Shifted( ecodes.KEY_EQUAL ) : key.Shifted( ecodes.KEY_SEMICOLON ),

    key.Shifted( ecodes.KEY_Q ) : key.Shifted( ecodes.KEY_Q ),
    key.Shifted( ecodes.KEY_W ) : key.Shifted( ecodes.KEY_W ),
    key.Shifted( ecodes.KEY_E ) : key.Shifted( ecodes.KEY_E ),
    key.Shifted( ecodes.KEY_R ) : key.Shifted( ecodes.KEY_R ),
    key.Shifted( ecodes.KEY_T ) : key.Shifted( ecodes.KEY_T ),
    key.Shifted( ecodes.KEY_Y ) : key.Shifted( ecodes.KEY_Y ),
    key.Shifted( ecodes.KEY_U ) : key.Shifted( ecodes.KEY_U ),
    key.Shifted( ecodes.KEY_I ) : key.Shifted( ecodes.KEY_I ),
    key.Shifted( ecodes.KEY_O ) : key.Shifted( ecodes.KEY_O ),
    key.Shifted( ecodes.KEY_P ) : key.Shifted( ecodes.KEY_P ),
    key.Shifted( ecodes.KEY_LEFTBRACE ) : key.Shifted( ecodes.KEY_RIGHTBRACE ),
    key.Shifted( ecodes.KEY_RIGHTBRACE ) : key.Shifted( ecodes.KEY_BACKSLASH ),
    key.Shifted( ecodes.KEY_BACKSLASH ) : key.Shifted( ecodes.KEY_YEN ),

    key.Shifted( ecodes.KEY_A ) : key.Shifted( ecodes.KEY_A ),
    key.Shifted( ecodes.KEY_S ) : key.Shifted( ecodes.KEY_S ),
    key.Shifted( ecodes.KEY_D ) : key.Shifted( ecodes.KEY_D ),
    key.Shifted( ecodes.KEY_F ) : key.Shifted( ecodes.KEY_F ),
    key.Shifted( ecodes.KEY_G ) : key.Shifted( ecodes.KEY_G ),
    key.Shifted( ecodes.KEY_H ) : key.Shifted( ecodes.KEY_H ),
    key.Shifted( ecodes.KEY_J ) : key.Shifted( ecodes.KEY_J ),
    key.Shifted( ecodes.KEY_K ) : key.Shifted( ecodes.KEY_K ),
    key.Shifted( ecodes.KEY_L ) : key.Shifted( ecodes.KEY_L ),
    key.Shifted( ecodes.KEY_SEMICOLON ) : key.Unshifted( ecodes.KEY_APOSTROPHE ),
    key.Shifted( ecodes.KEY_APOSTROPHE ) : key.Shifted( ecodes.KEY_2 ),

    key.Shifted( ecodes.KEY_Z ) : key.Shifted( ecodes.KEY_Z ),
    key.Shifted( ecodes.KEY_X ) : key.Shifted( ecodes.KEY_X ),
    key.Shifted( ecodes.KEY_C ) : key.Shifted( ecodes.KEY_C ),
    key.Shifted( ecodes.KEY_V ) : key.Shifted( ecodes.KEY_V ),
    key.Shifted( ecodes.KEY_B ) : key.Shifted( ecodes.KEY_B ),
    key.Shifted( ecodes.KEY_N ) : key.Shifted( ecodes.KEY_N ),
    key.Shifted( ecodes.KEY_M ) : key.Shifted( ecodes.KEY_M ),
    key.Shifted( ecodes.KEY_COMMA ) : key.Shifted( ecodes.KEY_COMMA ),
    key.Shifted( ecodes.KEY_DOT ) : key.Shifted( ecodes.KEY_DOT ),
    key.Shifted( ecodes.KEY_SLASH ) : key.Shifted( ecodes.KEY_SLASH ),

    key.Shifted( ecodes.KEY_ESC ) : key.Shifted( ecodes.KEY_ESC ),
    key.Shifted( ecodes.KEY_BACKSPACE ) : key.Shifted( ecodes.KEY_BACKSPACE ),
    key.Shifted( ecodes.KEY_ENTER ) : key.Shifted( ecodes.KEY_ENTER ),
    key.Shifted( ecodes.KEY_SPACE ) : key.Shifted( ecodes.KEY_SPACE ),
}
